### ISSUE TITLE
Sound does not play

### ISSUE THREAD

**Issue by Quezler** [nitnelave/CreeperHeal#45]

**Comment by Quezler** [comment]
Sound does not play even if you have the config set correctly as mentioned in #38

**Comment by Quezler** [comment]
```
# 
# CreeperHeal v 6.0
wait-before-heal:
  explosions: 10
  fire: 45
block-per-block:
  enabled: true
  interval: 1
replace-protected-chests-immediately: false
crack-destroyed-bricks: false
replace-grass-with-dirt: false
sound:
  volume: 1
  type: ITEM_PICKUP

```
