### ISSUE TITLE
Explosions not healing with whitelist enabled

### ISSUE THREAD

**Issue by notmateo** [nitnelave/CreeperHeal#76]
When a creeper explodes with the whitelist enabled, no blocks heal at all. With it disabled it works perfectly fine. I have it only set to grass and dirt but it's not healing either. Not sure what else to add, but here's my current advanced.yml config file for 'world':

```
restrict:
  use-whitelist: true
  blacklist: '0'
  whitelist: '2, 3'
replace-grass-with-dirt: false
repair-time-of-day: -1
protected-list: '0'
factions:
  ignore-wilderness: false
  ignore-territory: false
drop-chest-contents: false
```
